"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['launcher.py']
DATA_FILES = []
OPTIONS = {  'argv_emulation': True,
    'iconfile': 'icon.jpg',  # optional: include if you want app icon
    'packages': ['cohere'],  # list all required packages
    'includes': ['tkinter'],  # if you're using Tkinter or similar}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
